# Site settings
title: Kim Sangwon
email: pueuepueue@gmail.com
description: Nobody cares how it works as long as it works
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pueue.com" # the base hostname & protocol for your site
twitter_username: pueuepueue
github_username:  pueue

# Build settings
markdown: kramdown

permalink: "/:title"
paginate: 10

defaults:
    -
        scope:
            path: "" # 여기에서 빈 문자열은 프로젝트 내의 모든 파일을 의미합니다
        values:
            layout: "post"
